# Start the service with the command 'docker-compose up -d'

version: '2'

services:
  p2wdb-mongodb:
    image: mongo:4.4.2-bionic
    container_name: p2wdb-mongo
    ports:
      - '172.17.0.1:5666:27017' # <host port>:<container port>
    volumes:
      - ../data/mongodb:/data/db
    command: mongod --logpath=/dev/null # -- quiet
    restart: always

  p2wdb:
    build: .
    container_name: p2wdb
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '10'
    mem_limit: 500mb
    links:
      - p2wdb-mongodb
    ports:
      # <host port>:<container port>
      - 5667:5001 # REST API
      - 5668:5668 # IPFS TCP port
      - 5669:5669 # IPFS WS Port
    volumes:
      - ../data/ipfsdata:/home/safeuser/ipfs-p2wdb-service/.ipfsdata
    restart: always
